# Generated by Django 2.1.5 on 2019-01-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0002_auto_20190106_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ability_points',
            field=models.IntegerField(default=25),
        ),
    ]
