# Generated by Django 2.1.5 on 2019-01-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0003_character_ability_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterclass',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
