# Generated by Django 2.1.5 on 2019-01-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0006_race_constitution_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
    ]
