# Generated by Django 2.1.5 on 2019-01-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0008_character_constitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='charisma_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='dexterity_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='intelligence_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='strength_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='wisdom_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='constitution_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
