# Generated by Django 2.1.5 on 2019-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0010_auto_20190109_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='athletics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge_arcana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge_world',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lore_nature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lore_religion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='mobility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='persuasion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='stealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trickery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='use_magic_device',
            field=models.IntegerField(default=0),
        ),
    ]
