# Generated by Django 2.1.5 on 2019-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0011_auto_20190110_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='skills_per_level',
            field=models.IntegerField(default=0),
        ),
    ]
