# Generated by Django 2.1.5 on 2019-01-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactergenerator', '0013_race_skilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skilled',
            field=models.BooleanField(default=False),
        ),
    ]
